config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'


  namespace :admin do
    resources :places, except: :index do
      get :change_image  
      resources :images, controller: 'place_images'
    end
  end


  # get 'areas/index'
  resources :places, only: :show

  root 'places#index'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
  before_validation :set_slug

  has_many :place_images, class_name: 'PlaceImage'
  validates :ja_name, uniqueness: true, presence: true
  validates :en_name, uniqueness: true, presence: true
  validates :slug, uniqueness: true, presence: true

  def set_slug
    self.slug = self.en_name.downcase.gsub(/&/, "and").gsub(/ /, "-").gsub(/'/, "")
  end

  def image?
  end

  def image
    image = PlaceImage.find_by(id: image_id)
    image.present? ? image = image.image.url : '/no-image.png'
  end
end

app/models/place_image.rb
class PlaceImage < ApplicationRecord
  dragonfly_accessor :image

  belongs_to :place, class_name: 'Place'

  validates :image, presence: true

  validates :image, presence: true
  validates_size_of :image, maximum: 700.kilobytes, message: "It is too big, kya!!"

  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp],
                     message: "It's not my type", case_sensitive: false

end

app/controllers/admin/place_images_controller.rb
class Admin::PlaceImagesController < ApplicationController
  before_action :set_place
  layout 'admin'
  def index
    @images = @place.place_images.all
  end

  def create
    @image = @place.place_images.build(image: image_params[:file])
    if @image.save
      redirect_to admin_place_path(@place.slug), notice: 'コメント内容を更新しました'
    end
  end

  def destroy
    @image = PlaceImage.find_by(id: params[:id])
    @image.destroy
    redirect_to admin_place_path(@place), notice: 'コメント内容を更新しました'  
  end

  def change_image
    @place.update_column(@place.image_id, params[:image_id])
  end

  private

  def set_place
    @place = Place.find_by(id: params[:place_id])
    # render_not_found if @place.blank?

  end

  def image_params
    params.require(:place_image).permit(:file)
  end

  def object_params

  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def index
    @place = Place.all
  end

  def show
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to admin_place_path(@place), notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        # format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { render action: 'show', notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_image
    @place = Place.find_by(id: params[:place_id])
    if @place.update_column :image_id, params[:image_id]
      render action: 'show', status: :created, location: @place
    end
  end

  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.json { head :no_content }
    end
  end

  private
    def set_place
      @place = Place.where(slug: params[:id]).first
    end

    def place_params
      params.require(:place).permit(:ja_name, :ja_kana, :en_name,
        :category_id, :copy, :description, :city_id, :district_id,
        :vi_address, :ja_address, :en_address, :latitude, :longitude,
        :area_id, :keywords, :tel, :url, :access, :budget, :budget_lunch,
        :budget_dinner, :seats, :booking, :smoking, :open_at, :close_at, :holiday,
        :holiday_memo, :views, :views_in_week, :views_in_month, :prior, :published,
        :memo, :credit_cards, :shop_hour, :special_name, :score_bias, :email, :payment_for_reservation)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
  def index
  	@places = Place.all
    render template: 'admin/index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found
    return head :no_content if request.xhr?
    render template: 'errors/404.html', layout: 'layouts/application', status: :not_found
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place

  def index
    # @place = Place.all
  end

  def show 
  # @place = Place.all


  end

  private

    def set_place
      @place = Place.where(slug: params[:id]).first
      # raise ActiveRecord::RecordNotFound if @place.blank?
      # render root_path if @place.blank?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def root_path?
    request.path == "/"
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/admin/index.html.slim
h1 Admin
= link_to "New Place", new_admin_place_path
h2 list places
table.table.table-striped
  thead
    th #
    th =t("English name")
    th =t("Slug")
  - @places.each_with_index do |place, index|
    tr
      td.num= index + 1
      td = link_to place.en_name, place_path(place.slug)
      td = link_to place.slug, admin_place_path(place.slug)
      td = link_to t("Edit"), edit_admin_place_path(place.slug)
      td = link_to t("delete"), admin_place_path(place.slug), method: :delete, data: { confirm: '本当に削除しますか？' }

app/views/admin/place_images/index.html.slim
h1 place image
/ = params[]
p = admin_place_images_path
p = [:admin]
- guide_image = @place.place_images.build

= form_for admin_place_images_path(params[:place_id]) do |f|
  .form-group
    .row
      .col-md-3.text-right
      .col-md-8
        = f.file_field :file

  .actions = f.submit '保存する', class: 'btn btn-primary'

= form_for guide_image, url: admin_place_images_path(params[:place_id]) do |f|
  .form-group
    .row
      .col-md-3.text-right
      .col-md-8
        = f.file_field :file
  .actions = f.submit '保存する', class: 'btn btn-primary'

app/views/admin/places/_form.html.slim
= form_for [:admin, @place] do |f|
  h2 new places
  fieldset
    legend = 'basic infomation'
    / legend= t("基本情報")

    .form-group
      .row
        .col-md-3.text-right
          = f.label :ja_name
        .col-md-8
          = f.text_field :ja_name, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :ja_kana
        .col-md-8
          = f.text_field :ja_kana, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :en_name
        .col-md-8
          = f.text_field :en_name, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :category_id
        .col-md-8
          = f.select :category_id, Category.all.map{|category| [ t(category.en_name), category.id ] },
            include_blank: true
    .form-group
      .row
        .col-md-3.text-right
          = f.label :keywords
        .col-md-8
          = f.text_field :keywords, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :tel
        .col-md-8
          = f.text_field :tel, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :email
        .col-md-8
          = f.text_field :email, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :description
        .col-md-8
          = f.text_area :description, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :copy
    /     .col-md-8
    /       = f.text_field :copy, class: 'form-control'
  fieldset
    legend = 'local infomation'
    .form-group
      .row
        .col-md-offset-3
          .col-md-4
            = f.label :city_id, class: 'col-md-3 control-label'
            = f.select :city_id, City.all.map{|city| [ t(city.en_name), city.id ] },
              include_blank: true
          .col-md-4
            = f.label :district_id, class: 'col-md-3 control-label'
            = f.select :district_id, District.all.map{|district| [ t(district.en_name), district.id ] },
              include_blank: true
          .col-md-4
            = f.label :area_id, class: 'col-md-3 control-label'
            = f.select :area_id, Area.all.map{|area| [ t(area.en_name), area.id ] },
              include_blank: true
    .form-group
      .row
        .col-md-3.text-right
          = f.label :ja_address
        .col-md-8
          = f.text_field :ja_address, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :en_address
        .col-md-8
          = f.text_field :en_address, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :vi_address
        .col-md-8
          = f.text_field :vi_address, class: 'form-control'

    .form-group
      .row
        = label_tag "", "lat・long", class: 'col-sm-3 text-right control-label'
        .col-sm-4
          = f.text_field :latitude, class: 'form-control'
        .col-sm-4
          = f.text_field :longitude, class: 'form-control'

    .form-group
      .row
        .col-md-3.text-right
          = f.label :url
        .col-md-8
          = f.text_field :url, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :access
        .col-md-8
          = f.text_field :access, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :seats
    /     .col-md-8
    /       = f.text_field :category_id, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :booking
    /     .col-md-8
    /       = f.text_field :description, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :smoking
    /     .col-md-8
    /       = f.text_field :city_id, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :credit_cards
    /     .col-md-8
    /       = f.text_field :district_id, class: 'form-control'
  fieldset
    legend = t('Business hours etc.')
    .form-group
      .row
        .col-md-3.text-right
          = f.label :shop_hour
        .col-md-8
          = f.text_field :shop_hour, class: 'form-control'
    .form-group
      .row
        .col-md-3.text-right
          = f.label :holiday
        .col-md-8
          = f.text_field :holiday, class: 'form-control'
    / .form-group
      .row
        .col-md-3.text-right
          = f.label :image_id
        .col-md-8
          = f.text_field :en_address, class: 'form-control'
    / .form-group
    /   .row
    /     .col-md-3.text-right
    /       = f.label :published
    /     .col-md-8
    /       = f.text_field :latitude, class: 'form-control'

  .actions = f.submit '保存する', class: 'btn btn-primary'

app/views/admin/places/edit.html.slim
= render 'form'

app/views/admin/places/index.html.slim
h1 new
= link_to "New Place", new_admin_place_path
table.table.table-striped
  thead
    th JP name
    th EN name
  - @place.each do |place|
    tr
      td = place.ja_name
      td = place.slug
      / td.text-right= place.en_name
    = link_to t("Edit"), edit_admin_place_path(place.slug)

app/views/admin/places/new.html.slim
=render 'form'

app/views/admin/places/show.html.slim
h1= @place.ja_name

.row
  .place_body_left.col-md-8
    h2= t("basic infomation")
    table.table.table-striped
      tbody
        tr
          th= t("Japan name")
          td
            = @place.ja_name
        tr
          th= t("Kana name")
          td
            = @place.ja_kana
        tr
          th= t("En name")
          td
            = @place.en_name
        tr
          th= t("Category")
          td
            = @place.category_id
        tr
          th= t("Key words")
          td
            = @place.keywords
        tr
          th= t("Tel")
          td
            = @place.tel
        tr
          th= t("Email")
          td
            = @place.email
        tr
          th= t("Description")
          td
            = @place.description
    h2= t("local infomation")
    table.table.table-striped
      tbody
        tr
          th= t("City")
          td
            = @place.category_id
          th= t("District")
          td
            = @place.district_id
          th= t("Area")
          td
            = @place.area_id
        tr
          th= t("Japan address")
          td
            = @place.ja_address
        tr
          th= t("English address")
          td
            = @place.en_address
        tr
          th= t("Vietnamese address")
          td
            = @place.vi_address
        tr
          th= t("Latitude")
          td
            = @place.latitude
          th= t("Longitude")
          td
            = @place.longitude

        tr
          th= t("Url")
          td
            = @place.url
        tr
          th= t("access")
          td
            = @place.access
        / tr
        /   th= t("Created date")
        /   td= @place.created_at.to_s(:datetime)
    h2= t('Business hours etc.')
    table.table.table-striped
      tbody

        tr
          th= t("Shop hour")
          td
            = @place.shop_hour
        tr
          th= t("holiday")
          td
            = @place.holiday
  .place_body_right.dotted-left.col-lg-4
    - guide_image = @place.place_images.build
    / = form_for guide_image, url: admin_place_images_path(@place),
    /   multipart: true, html: { id: :admin_place_fileupload, class: 'fileupload' } do |f|
    /   span.btn.btn-default.fileupload-button
    /     | Drop image or click to upload
    /     = f.file_field :file

    .place_img style="background-repeat: no-repeat;background-size: cover;background-position: center;height: 300px ; background-image: url(#{@place.image}"

    = form_for guide_image, url: admin_place_images_path(@place.id) do |f|
      .form-group
        .row
          .col-md-3.text-right
          .col-md-8
            = f.file_field :file

      .actions = f.submit '保存する', class: 'btn btn-primary'
    ul.guide_content_images
      - @place.place_images.all.each do |images|
        li.image
          = link_to image_tag(images.image.url), class: 'img-thumbnail'
          .image_navi
            = link_to 'delete', admin_place_image_path(@place, images),
              remote: true, method: :delete, data: { confirm: '本当に削除しますか？' }
            = link_to 'change image', admin_place_change_image_path(@place,image_id: images)

    / = link_to "並べ替えた順番で再表示する", admin_place_images_path(@place), class: 'btn btn-link'

app/views/areas/index.html.slim
h1 高級ベトナム料理
p = "東南アジアといえば、まず思い当たるのが「物価の安さ」ではないでしょうか。ベトナムの物価は日本の3分の1から7分程度。欧米旅行では財布の紐をきつめにする方も、ベトナムでは贅沢な旅行を満喫することができます。そこで当サイトがおすすめする高級ベトナム料理レストランへ訪れてみてはいかがでしょうか。当カテゴリーで紹介している高級レストランは、現地人からすると正直値が張るため、そうそう行くことはかないません。しかしながら、日本人旅行者の皆さんにとっては、「この価格で高級レストランなんだ」、「この雰囲気と味でこの値段は安い」と感じることでしょう。日本では2013年頃から円安が進んでいますが、それでもベトナムでは何もかもが安く思え、学生旅行者の予算であっても、十分高級レストランに行くことができるはずです。毎夜足を運ぶ必要はありませんが、滞在中一度から二度は、贅沢な料理を高級感溢れる雰囲気の中でとってみてはいかがでしょうか。友人同士、家族、そして恋人カップルと客層は問いません。高級レストランといっても、服装指定のドレスコードがあるわけではないので、旅行用のラフな服装でどなたでも気軽に訪れることができるのも、ベトナム料理レストランの魅力。帰国後も思い出に残る時間を過ごすため、是非ここで紹介しているおすすめ高級レストランに足を運んでみてください。"

app/views/layouts/_slide.html.slim
.banner_top.carousel.slide data-ride="carousel" 
  .carousel-inner
    .carousel-item.active
      img alt=("Los Angeles") src="banner675x355/banner4.jpg" /
      .carousel-caption
        h3 Los Angeles
        p We had such a great time in LA!
    .carousel-item
      img alt="Chicago" src="banner675x355/banner2.jpg" /
      .carousel-caption
        h3 Chicago
        p Thank you, Chicago!
    .carousel-item
      img alt=("New York") src="banner675x355/banner3.jpg" /
      .carousel-caption
        h3 New York
        p We love the Big Apple!
  a.carousel-control-prev data-slide="prev" href=".carousel.slide" 
    span.carousel-control-prev-icon
  a.carousel-control-next data-slide="next" href=".carousel.slide"
    span.carousel-control-next-icon

app/views/layouts/admin.html.slim
doctype html
html lang="en"
  head
    title Mainichi Spa - Admin
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body.admin
    #container.row
      #left_bar.col-lg-2
        .box
          h2.category_title
            = link_to 'Admin', admin_path
          = link_to "Place" , admin_path 
      #main.col-lg-10
        h2 admin
        = yield

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    / title Mainichispa
    = stylesheet_link_tag :application
    title Bootstrap Example
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" /
    script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" 
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" 
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
  body
    header
      = link_to root_path do 
        .container
          .header_inner
            .header_logo
              h1 = "Mainichi Spa"
    = render partial: "layouts/slide" if root_path?

    #container.row
      #left_bar.col-lg-2.col-md-2.hidden-sm.hidden-xs
        .box.category_menu
          h2.category_title 記事
          .category_menu_item
            = link_to root_path do
              span.iconCategory.icon-home
              span Home
          .category_menu_item
            = link_to '/areas/index' do
              span.iconCategory.icon-spa
              span Spa
          .category_menu_item
            = link_to '/areas/index' do
              span.iconCategory.icon-salon
              span Salon
          .category_menu_item
            = link_to '/areas/index' do
              span.iconCategory.icon-nail
              span Nail
          .category_menu_item
            = link_to '/areas/index' do
              span.iconCategory.icon-love
              span Love
          .line

        .box
          h2.category_title Ho Chi Minh
          ul
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
          .line

        .box
          h2.category_title Ha Noi
          ul
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
            li Quan 1
          .line

      #main.col-lg-10.col-md-12.col-sm-12.col-xs-12
        - unless root_path?
          .topbar
            ul#breadcrumb
              li
                = link_to root_url do
                  span MainichiSpa
              li
                = link_to root_url do
                  span MainichiSpa
        = yield
                


      #footer

app/views/page/index.html.slim
.contriner
  .row
    .col-sm-6 style="background-color: red; height: 10px;"
    .col-sm-6 style="background-color: green; height: 10px;"
    	h1 blabla

app/views/places/_index.html.slim
.main_content
  h2.title Ranking gi day 
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        .place_content
          .place_img style="background-image: url(banner675x355/banner4.jpg)"
          .place_text
            h2.line Spa  
            p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)
.main_content
  h2.title List Spa
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        .place_content
          .place_img style="background-image: url(banner675x355/banner4.jpg)"
          .place_text
            h2.line Spa  
            p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)
.main_content
  h2.title List Salon
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        .place_content
          .place_img style="background-image: url(banner675x355/banner4.jpg)"
          .place_text
            h2.line Spa  
            p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)

app/views/places/demo.html.slim
.row.box.dotted-bottom
  .place_info_img.col-lg-7
    .place_img
    .place_img_slide
    /   - (0..5).each
    /     .slide_item.col-lg-2.hidden-xs
    /       img style="background-image: url(/banner675x355/2018817194851593.jpg)"
  .place_info.col-lg-5
    .info_title
      h2 = "エミスパ"
      h4 = "Emi Spa"
    .line
    .info_content
      p
        span.glyphicon.glyphicon-map-marker
        = "52 Dong Du St. Dist.1. Ho Chi Minh"
      p
        span.glyphicon.glyphicon-earphone
        = "028 3939 0052"
      p
        span.glyphicon.glyphicon-time
        = "10:00～24:00※24時にコースは終了"
      p
        span.glyphicon.glyphicon-credit-card
        = "Visa,Master,JCB,AMEX"
      p
        span.glyphicon.glyphicon-tags
        = "ホーチミン,市民劇場・ドンコイエリア,立地抜群,贅沢・高級,クーポン,カップル,女子旅,サウナ,日本語対応"
  
  

.row.box
  .place_body_left.col-lg-8
    h2 店舗メニュー
    .line
    -(0..2).each do ||
      .place_item.row
        .item_img.col-md-5 style="background-image: url(/banner675x355/2018817194851593.jpg)"
        .item_content.col-md-7
          .item_title
            h2 = "笑みコース（4時間）"
            h4 = "Emi Course(4h)"
          .item_text
            .item_des
              = "エミスパのフルコース・パッケージ。半日かけて肩こり、アンチエイジング、フットケアを行う贅沢なコース。ホーチミン観光のハイライトとして最後にとっておくのはいかがでしょうか。女子旅でもカップルでも一生の思い出になること間違いありません。"

              .box_item
                h3 コース内容
                = "1．サウナ"
                br
                = "2．痛みの緩和マッサージ"
                br
                ="3．コラーゲンパックでアンチエイジング"
                br
                ="4．ホットストーン・フットマッサージ"
                br
                ="5．パラフィンセラピー（手or足）"
                br
                ="6．マニキュアorペディキュア"
      .line


  .place_body_right.dotted-left.col-lg-4.col-xs-12

app/views/places/index.html.slim
.main_content
  h2.title Ranking gi day 
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        = link_to "/hochiminh/spa/test" do
          .place_content
            .place_img style="background-image: url(banner675x355/2018817194851593.jpg)"
            .place_text
              h2.line Spa  
              p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)
.main_content
  h2.title List Spa
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        .place_content
          .place_img style="background-image: url(banner675x355/banner4.jpg)"
          .place_text
            h2.line Spa  
            p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)
.main_content
  h2.title List Salon
  .row
    - (0..7).each do ||
      .box_place.col-lg-3.col-sm-4.col-xs-3
        .place_content
          .place_img style="background-image: url(banner675x355/banner4.jpg)"
          .place_text
            h2.line Spa  
            p = truncate("day la 1 cai spa nao do nam o dau khong biet nua ", length: 130)

app/views/places/show.html.slim
.row.box.dotted-bottom
  .place_info_img.col-lg-7
    .place_img style="background-image: url(#{@place.image})"
    .place_img_slide
    /   - (0..5).each
    /     .slide_item.col-lg-2.hidden-xs
    /       img style="background-image: url(/banner675x355/2018817194851593.jpg)"
  .place_info.col-lg-5
    .info_title
      h2 = @place.ja_name
      h4 = @place.en_name
    .line
    .info_content
      p
        span.glyphicon.glyphicon-map-marker
        = @place.en_address
      p
        span.glyphicon.glyphicon-earphone
        = @place.tel
      p
        span.glyphicon.glyphicon-time
        = @place.shop_hour
      p
        span.glyphicon.glyphicon-credit-card
        = @place.credit_cards
      p
        span.glyphicon.glyphicon-tags
        = @place.keywords
  
  

/ .row.box
/   .place_body_left.col-lg-8
/     h2 店舗メニュー
/     .line
/     -(0..2).each do ||
/       .place_item.row
/         .item_img.col-md-5 style="background-image: url(/banner675x355/2018817194851593.jpg)"
/         .item_content.col-md-7
/           .item_title
/             h2 = "笑みコース（4時間）"
/             h4 = "Emi Course(4h)"
/           .item_text
/             .item_des
/               = "エミスパのフルコース・パッケージ。半日かけて肩こり、アンチエイジング、フットケアを行う贅沢なコース。ホーチミン観光のハイライトとして最後にとっておくのはいかがでしょうか。女子旅でもカップルでも一生の思い出になること間違いありません。"

/               .box_item
/                 h3 コース内容
/                 = "1．サウナ"
/                 br
/                 = "2．痛みの緩和マッサージ"
/                 br
/                 ="3．コラーゲンパックでアンチエイジング"
/                 br
/                 ="4．ホットストーン・フットマッサージ"
/                 br
/                 ="5．パラフィンセラピー（手or足）"
/                 br
/                 ="6．マニキュアorペディキュア"
/       .line


/   .place_body_right.dotted-left.col-lg-4.col-xs-12